/*
 * generated by Xtext
 */
package ch.unige.cui.smv.stratagem.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TransitionSystemDslRuntimeModule extends ch.unige.cui.smv.stratagem.xtext.AbstractTransitionSystemDslRuntimeModule {
	// contributed by org.eclipse.xtext.generator.exporting.SimpleNamesFragment 
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return ch.unige.cui.smv.stratagem.xtext.naming.MyNameProvider.class;
	}
}
