/*
* generated by Xtext
*/
package ch.unige.cui.smv.stratagem.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TransitionSystemDslStandaloneSetup extends TransitionSystemDslStandaloneSetupGenerated{

	public static void doSetup() {
		new TransitionSystemDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

