<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ts" nsURI="http://cui.unige.ch/smv/transitionsystem.ecore" nsPrefix="ts">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="adt_0" value="http://cui.unige.ch/smv/adt.ecore#/"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adt" lowerBound="1" eType="ecore:EClass ../../ch.unige.cui.smv.metamodel.adt/model/adt.ecore#//ADT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" lowerBound="1"
        eType="ecore:EClass ../../ch.unige.cui.smv.metamodel.adt/model/adt.ecore#//ATerm"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="1"
        upperBound="-1" eType="#//DeclaredStrategy" volatile="true" derived="true"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#strats"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auxiliary" upperBound="-1"
        eType="#//DeclaredStrategy" volatile="true" derived="true" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#strats"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strats" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry"
        transient="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="group"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredStrategy">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueVariableParameters ValidFormalParams"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="UniqueVariableParameters" value="Tuple {&#xA;&#x9;message : String = 'The parameter names are not unique for declared strategy: ' + name,&#xA;&#x9;status : Boolean = formalParams&#xA;&#x9;&#x9;&#x9;&lt;> null implies formalParams&#xA;&#x9;&#x9;&#x9;->isUnique(name)&#xA;}.status"/>
      <details key="ValidFormalParams" value="Tuple {&#xA;&#x9;message : String = 'Formal params for strategy ' + name + ' are null',&#xA;&#x9;status : Boolean = formalParams &lt;> null&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//NonVariableStrategy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formalParams" upperBound="-1"
        eType="#//VariableStrategy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonVariableStrategy" abstract="true"
      eSuperTypes="#//Strategy"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableStrategy" eSuperTypes="#//Strategy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identity" eSuperTypes="#//NonVariableStrategy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fail" eSuperTypes="#//NonVariableStrategy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Choice" eSuperTypes="#//NonVariableStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="S1" lowerBound="1" eType="#//Strategy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="S2" lowerBound="1" eType="#//Strategy"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredStrategyInstance" eSuperTypes="#//NonVariableStrategy">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="RightNumberOfParams"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="RightNumberOfParams" value="Tuple {&#xA;&#x9;message : String = 'Invalid number of parameters for strategy ' + name + '. Required ' +&#xA;&#x9;&#x9;&#x9;declaration.formalParams&#xA;&#x9;&#x9;&#x9;->size()&#xA;&#x9;&#x9;&#x9;->toString() + ', found ' + actualParams&#xA;&#x9;&#x9;&#x9;->size()&#xA;&#x9;&#x9;&#x9;->toString(),&#xA;&#x9;status : Boolean = (declaration &lt;> null) implies declaration.formalParams&#xA;&#x9;&#x9;&#x9;->size() = actualParams&#xA;&#x9;&#x9;&#x9;->size()&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
        eType="#//DeclaredStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualParams" upperBound="-1"
        eType="#//Strategy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FixPointStrategy" eSuperTypes="#//NonVariableStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="S" lowerBound="1" eType="#//Strategy"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfThenElse" eSuperTypes="#//NonVariableStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="S1" lowerBound="1" eType="#//Strategy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="S2" lowerBound="1" eType="#//Strategy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="S3" lowerBound="1" eType="#//Strategy"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//NonVariableStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="S" lowerBound="1" eType="#//Strategy"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="One" eSuperTypes="#//NonVariableStrategy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="S" lowerBound="1" eType="#//Strategy"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Saturation" eSuperTypes="#//NonVariableStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="S" lowerBound="1" eType="#//Strategy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//NonVariableStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="S1" lowerBound="1" eType="#//Strategy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="S2" lowerBound="1" eType="#//Strategy"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Union" eSuperTypes="#//NonVariableStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="S1" lowerBound="1" eType="#//Strategy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="S2" lowerBound="1" eType="#//Strategy"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleStrategy" eSuperTypes="#//NonVariableStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="equations" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../ch.unige.cui.smv.metamodel.adt/model/adt.ecore#//Equation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="All" eSuperTypes="#//NonVariableStrategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="S" lowerBound="1" eType="#//Strategy"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
