language: scala
scala:
   - 2.10.6
   - 2.10.5
   - 2.10.4
   - 2.10.3
   - 2.10.2

jdk:
  - openjdk7
  - oraclejdk8

os:
  - linux
  - osx

matrix:
  allow_failures:
  - os: osx

script:
   - cd stratagem
   - sbt ++$TRAVIS_SCALA_VERSION test
