/*
 * generated by Xtext
 */
package ch.unige.cui.smv.stratagem.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTransitionSystemDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://cui.unige.ch/smv/transitionsystem.ecore"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://cui.unige.ch/smv/adt.ecore"));
		return result;
	}
}
