/*
 * generated by Xtext
 */
package ch.unige.cui.smv.stratagem.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ch.unige.cui.smv.stratagem.xtext.ui.internal.TransitionSystemDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TransitionSystemDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TransitionSystemDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TransitionSystemDslActivator.getInstance().getInjector(TransitionSystemDslActivator.CH_UNIGE_CUI_SMV_STRATAGEM_XTEXT_TRANSITIONSYSTEMDSL);
	}
	
}
