/*
 * generated by Xtext
 */
package ch.unige.cui.smv.stratagem.xtext.ui.contentassist

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TransitionSystemDslProposalProvider extends AbstractTransitionSystemDslProposalProvider {

}
