/*
* generated by Xtext
*/
package ch.unige.cui.smv.stratagem.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ch.unige.cui.smv.stratagem.xtext.services.TransitionSystemDslGrammarAccess;

public class TransitionSystemDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TransitionSystemDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected ch.unige.cui.smv.stratagem.xtext.parser.antlr.internal.InternalTransitionSystemDslParser createParser(XtextTokenStream stream) {
		return new ch.unige.cui.smv.stratagem.xtext.parser.antlr.internal.InternalTransitionSystemDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TransitionSystem";
	}
	
	public TransitionSystemDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TransitionSystemDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
