<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="adt" nsURI="http://cui.unige.ch/smv/adt.ecore" nsPrefix="adt">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ADT">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueVariableNames"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="UniqueVariableNames" value="Tuple {&#xA;&#x9;message : String = 'The following variables are defined more than once: ' + variables&#xA;&#x9;&#x9;&#x9;->select(v | (variables&#xA;&#x9;&#x9;&#x9;&#x9;->select(v1 | (v1.name = v.name))&#xA;&#x9;&#x9;&#x9;&#x9;->size() > 1))&#xA;&#x9;&#x9;&#x9;->collect(name)&#xA;&#x9;&#x9;&#x9;->toString(),&#xA;&#x9;status : Boolean = variables&#xA;&#x9;&#x9;&#x9;->isUnique(name)&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="adt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
        eType="#//Signature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//VariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equations" upperBound="-1"
        eType="#//Equation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASort" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NameNotEmpty"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NameNotEmpty" value="Tuple {&#xA;&#x9;message : String = 'Cannot assign empty name to sort',&#xA;&#x9;status : Boolean = name &lt;> ''&#xA;}.status"/>
    </eAnnotations>
    <eOperations name="isSubSortOf" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="sort" eType="#//ASort"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="s"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubSort" eSuperTypes="#//ASort">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SuperSortNotNull"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="SuperSortNotNull" value="Tuple {&#xA;&#x9;message : String = 'The super sort of sort ' + name + 'cannot be null',&#xA;&#x9;status : Boolean = superSort &lt;> null&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superSort" lowerBound="1"
        eType="#//ASort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sort" eSuperTypes="#//ASort"/>
  <eClassifiers xsi:type="ecore:EClass" name="Signature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueSorts UniqueOperations"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="UniqueSorts" value="Tuple {&#xA;&#x9;message : String = 'There are some sorts in the adt that appear more than once: ' + sorts&#xA;&#x9;&#x9;&#x9;->select(s1 | (sorts&#xA;&#x9;&#x9;&#x9;&#x9;->select(s2 | (s2.name = s1.name))&#xA;&#x9;&#x9;&#x9;&#x9;->size() > 1))&#xA;&#x9;&#x9;&#x9;->collect(name)&#xA;&#x9;&#x9;&#x9;->toString(),&#xA;&#x9;status : Boolean = sorts &lt;> null implies sorts&#xA;&#x9;&#x9;&#x9;->isUnique(name)&#xA;}.status"/>
      <details key="UniqueOperations" value="Tuple {&#xA;&#x9;message : String = 'There are some operations in the adt that appear more than once: ' + allOperations&#xA;&#x9;&#x9;&#x9;->select(op1 | (allOperations&#xA;&#x9;&#x9;&#x9;&#x9;->select(op2 | (op2.name = op1.name))&#xA;&#x9;&#x9;&#x9;&#x9;->size() > 1))&#xA;&#x9;&#x9;&#x9;->collect(name)&#xA;&#x9;&#x9;&#x9;->toString(),&#xA;&#x9;status : Boolean = allOperations&#xA;&#x9;&#x9;&#x9;->isUnique(name)&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ops" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry"
        transient="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="group"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allOperations" upperBound="-1"
        eType="#//Operation" changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Decorator for all operations. It allows to get all operations in one list."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sorts" lowerBound="1" upperBound="-1"
        eType="#//ASort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" volatile="true" derived="true" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#ops"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generators" lowerBound="1"
        upperBound="-1" eType="#//Operation" volatile="true" derived="true" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#ops"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NameNotEmpty"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NameNotEmpty" value="name &lt;> ''"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sort" lowerBound="1" eType="#//ASort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="v"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidReturnType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidReturnType" value="Tuple {&#xA;&#x9;message : String = 'The return type for operation ' + name + ' was not set.',&#xA;&#x9;status : Boolean = returnType &lt;> null&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
        eType="#//ASort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formalParameters" unique="false"
        upperBound="-1" eType="#//ASort">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="group" value="#params"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="op"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="ATerm" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adt" lowerBound="1" eType="#//ADT"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sort" lowerBound="1" eType="#//ASort"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term" eSuperTypes="#//ATerm">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="CorrectNumberOfParameters CorrectTypeOfParameters RightAdtSubterms"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="CorrectNumberOfParameters" value="Tuple {&#xA;&#x9;message : String = 'Invalid number of parameters for term: ' + self.toString() + '. Required ' +&#xA;&#x9;&#x9;&#x9;operationSymbol.formalParameters&#xA;&#x9;&#x9;&#x9;->size()&#xA;&#x9;&#x9;&#x9;->toString() + ', found ' + subterms&#xA;&#x9;&#x9;&#x9;->size()&#xA;&#x9;&#x9;&#x9;->toString(),&#xA;&#x9;status : Boolean = (operationSymbol &lt;> null) implies subterms&#xA;&#x9;&#x9;&#x9;->size() = operationSymbol.formalParameters&#xA;&#x9;&#x9;&#x9;->size()&#xA;}.status"/>
      <details key="CorrectTypeOfParameters" value="Tuple {&#xA;&#x9;message : String = 'Invalid type of parameters for term: ' + self.toString(),&#xA;&#x9;status : Boolean = subterms &lt;> null&#xA;&#x9;&#x9;&#x9;implies subterms&#xA;&#x9;&#x9;&#x9;->forAll(p | ((p.sort &lt;> null) and (operationSymbol &lt;> null)) implies&#xA;&#x9;&#x9;&#x9;&#x9;p.sort.isSubSortOf(operationSymbol.formalParameters&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;->at(subterms&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;->indexOf(p))))&#xA;}.status"/>
      <details key="RightAdtSubterms" value="Tuple {&#xA;&#x9;message : String = 'Some subterms do not have the same adt as the parent term: ' +&#xA;&#x9;&#x9;&#x9;self.toString(),&#xA;&#x9;status : Boolean = (subterms &lt;> null) implies subterms&#xA;&#x9;&#x9;&#x9;->forAll(t | t.adt = self.adt)&#xA;}.status"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationSymbol" lowerBound="1"
        eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subterms" upperBound="-1"
        eType="#//ATerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//ATerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="#//VariableDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftHandTerm" lowerBound="1"
        eType="#//ATerm" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightHandTerm" lowerBound="1"
        eType="#//ATerm" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
