/*
* generated by Xtext
*/
package ch.unige.cui.smv.stratagem.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TransitionSystemDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ch.unige.cui.smv.stratagem.xtext.ui.internal.TransitionSystemDslActivator.getInstance().getInjector("ch.unige.cui.smv.stratagem.xtext.TransitionSystemDsl");
	}
	
}
