/*
 * generated by Xtext
 */
package ch.unige.cui.smv.stratagem.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TransitionSystemDslUiModule extends ch.unige.cui.smv.stratagem.xtext.ui.AbstractTransitionSystemDslUiModule {
	public TransitionSystemDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
